#!/system/bin/sh

/system/bin/log -t RIL.muxd.stop "calling stop_muxd......'$1'"

# make sure muxd is running before killing
if ls /data/rril/muxd.pid > /dev/null 2>&1; then

    MUXD_PID="$(cat /data/rril/muxd.pid)"
    /system/bin/log -t RIL.muxd.stop "muxd pid='$MUXD_PID'"

    kill -$1 $MUXD_PID

else
    /system/bin/log -t RIL.muxd.stop "muxd.pid not found: muxd not running!"
    exit 1

fi
